### ISSUE TITLE
lacks “diversity” 

### ISSUE THREAD

**Issue by tbrowder** [perl6/marketing#18]
Need pictures of some more users with other than light-colored skin. I would also emphasize youths (including a boy) since I believe they are the future of Perl 6.

**Comment by JJ** [comment]
Maybe we can take a few next TPC in Glasgow.

**Comment by tbrowder** [comment]
Good idea!

**Comment by zoffixznet** [comment]
Fuck racism.

The [stock we use](https://github.com/perl6/marketing/tree/master/STOCK/PAID) is chosen based on the aesthetic merit of the photos, not on the skin colour of the models featured.

**Comment by tbrowder** [comment]
Given the climate of societal dialog theses days, that may not be the wisest decision, although I agree with your sentiment (but not your choice of words).

**Comment by JJ** [comment]
We can use Creative-Commons, or even public domain, pictures that offer that picture of diversity with which I very much agree. Or, as said, take some pictures in the conference (although I must confess that diversity there is not too high, as fas as I have seen...)

**Comment by JJ** [comment]
For instance, all of [Wendy van Dijk's pictures](https://www.flickr.com/photos/wendyga/) are available with a creative commons license.

**Comment by zoffixznet** [comment]
> Given the climate of societal dialog these days

I'm not going to support a racist ideology regardless of the "climate".

**Comment by Ovid** [comment]
Given the photos which showed up in the marketing, I was surprised to see the stock photos had more diversity than I expected.

That being said, using highly inflammatory language such as words such as "racist ideology" in response to people politely asking for more diversity isn't particularly good for Perl 6 marketing.

**Comment by lizmat** [comment]
FWIW, I agree with Ovid's point re "using highly inflammatory language".

**Comment by pmichaud** [comment]
Ditto for me as well regarding the language used; plus "locking the conversation" and declaring diversity discussions as "off topic" with respect to marketing feels very much against Perl 6 culture (at least the one I remember).

Pm

**Comment by finanalyst** [comment]
It's possible all the contributors to this thread share a similar 
sympathy to inclusiveness but express it in different ways. So, for one 
viewpoint, having people of different coloured skin in pictures 
increases diversity. For another viewpoint just noticing skin colour as 
important is racist (after all we don't care what colour hair, or what 
colour eyes people have!).

But for marketing, the aim is to get people to identify with what is 
being promoted. 'Black panther' was hugely successful because it showed 
black people as superheros, which little black girls and boys could 
identify with and made the film special to them.

So if we *want* perl6 to be attractive to as wide an audience as 
possible, we *should* include photos that as wide an audience will 
identify with, so there should be girls, and women, as well as boys and 
men, and the girls should be doing the coding, not watching a guy code. 
And since skin colour in Africa and the shape of eyes (Asian vs 
European/African) in Asia are important definers of identity, we should 
choose photos with people having those characteristics.

As for "aesthetically pleasing", that too is a prejudice. I prefer TV 
programming from countries like UK and Netherlands because they have 
actors who look like normal people. US TV programs are full of 
abnormally beautiful actors - obviously unreal.

It is not racism when you choose photos that your target audience 
identifies with, it is savvy marketing.

**Comment by zaucker** [comment]
I don’t think “aesthetically pleasing” implies “beautiful people” (whatever that metric might be).
We try to use “aesthetically pleasing” pictures of ourselves on our company website, both to make it more “personal” and so that visitors “see” who we are. We (at least I) don’t think we are all super models just because of that.
Unfortunately so far we were not successful in hiring women for our company and we also didn’t have any none-caucasian applicants either.
I don’t think it would make sense to pretend to be a multi-cultural company by choosing pictures with people not part of the company.
Although I understand the marketing aspect, I would strongly suggest to not use “artificial” pictures. We (the Perl6 community) are who we are. And I also would strongly recommend to use good quality pictures (as Perl6 wants to be a high quality language).
So, by all means let’s take many pictures showing off the Perl(6) community and then choose good ones from that with as much diversity as there is.
Cheers,
Fritz

Fritz Zaucker
Platanen 42
4600 Olten
+41 62 212 7712
+41 79 675 0630

**Comment by finanalyst** [comment]
If you do not understand a metric for 'beautiful people', how then do 
you have one for 'aesthetically pleasing'? They are both subjective 
categories that are intrinsically difficult to define, but which most 
people can use.

"We use ... pictures of ourselves'! And 'we were not successful in 
hiring women ... non-caucasian ...' Perhaps you do not have a good 
approach? In my company I have a woman engineer who is far better than 
any of the male engineers we hired before, but we had to argue hard to 
hire her because of an inherent prejudice that women cant be engineers!!!

'Pictures of ourselves' in a company is rather different to 'pictures of 
ourselves' in a community like the perl6 one, which is almost inherently 
online and virtual. And the perl6 community is definitely multicultural. 
We have contributors from Europe, America and Asia that I can identify. 
So it would not be 'pretending' to have images of people  from those 
regions. I would be quite happy to have pictures of actual perl6 users, 
rather than 'aesthetically pleasing' stock photos.  Why not use pictures 
from YAPC's and hackathons?

Richard Hainsworth

Hong Kong.

**Comment by zaucker** [comment]
I do agree that we should not use stock photos. Larry instead of Richard Gere, Jonathan instead of Sean Connery, Liz and Wendy instead of The Netherlands next super model, etc.

Btw, some Perl6 community members are hard to identify at all, because they only appear with cute nick names and photos are hard to find if at all. Not sure what that means, I’d prefer to “know” the faces behind.

I did say “let’s take many pictures and select aesthetically pleasing ones”. With that I meant “high quality photos” (yes, that might be subjective to some degree as well), but not “beauty” of the content (for which there will probably be no common definition).

As we are a small company there is no resistance of bias against gender (whatever that might include) nor skin color to overcome as far as I can tell. There might be other non-technical biases (or rather selection criteria) such as ability to communicate not only on a technical but also personal level and preferences (like language).

And as I said, not having any applications by women just makes the whole point mute.

Cheers,
Fritz

Fritz Zaucker
Platanen 42
4600 Olten
+41 62 212 7712
+41 79 675 0630

**Comment by pmurias** [comment]
It seems to me it would be better if people focused on producing variant
marketing materials (so people choose which to use) with diverse photos. I
feel a honest pragmatic conversation about some of the trade-offs could get
too politically incorrect at least for my comfort.

W dniu wtorek, 14 sierpnia 2018 Michael D. Stemle, Jr. <
notifications@github.com> napisał(a):

> It seems ironic that this thread is its own diversity problem. I’m not
> trying to call anybody out, but several comments have been problematic, and
> I don’t think any offense or prejudice was intended. Instead I think we
> have a clear lack of experience in this matter.
>
> We should probably seek expert help on this, surely someone knows a
> professor or social worker with experience in this field.
>
> ~ Michael D. Stemle, Jr.
>
> > On Aug 14, 2018, at 02:44, Fritz Zaucker <notifications@github.com>
> wrote:
> >
> > I do agree that we should not use stock photos. Larry instead of Richard
> Gere, Jonathan instead of Sean Connery, Liz and Wendy instead of The
> Netherlands next super model, etc.
> >
> > Btw, some Perl6 community members are hard to identify at all, because
> they only appear with cute nick names and photos are hard to find if at
> all. Not sure what that means, I’d prefer to “know” the faces behind.
> >
> > I did say “let’s take many pictures and select aesthetically pleasing
> ones”. With that I meant “high quality photos” (yes, that might be
> subjective to some degree as well), but not “beauty” of the content (for
> which there will probably be no common definition).
> >
> > As we are a small company there is no resistance of bias against gender
> (whatever that might include) nor skin color to overcome as far as I can
> tell. There might be other non-technical biases (or rather selection
> criteria) such as ability to communicate not only on a technical but also
> personal level and preferences (like language).
> >
> > And as I said, not having any applications by women just makes the whole
> point mute.
> >
> > Cheers,
> > Fritz
> >
> > Fritz Zaucker
> > Platanen 42
> > 4600 Olten
> > +41 62 212 7712
> > +41 79 675 0630
> >
> > > On 14 Aug 2018, at 06:56, Richard Hainsworth <notifications@github.com>
> wrote:
> > >
> > > If you do not understand a metric for 'beautiful people', how then do
> > > you have one for 'aesthetically pleasing'? They are both subjective
> > > categories that are intrinsically difficult to define, but which most
> > > people can use.
> > >
> > > "We use ... pictures of ourselves'! And 'we were not successful in
> > > hiring women ... non-caucasian ...' Perhaps you do not have a good
> > > approach? In my company I have a woman engineer who is far better than
> > > any of the male engineers we hired before, but we had to argue hard to
> > > hire her because of an inherent prejudice that women cant be
> engineers!!!
> > >
> > > 'Pictures of ourselves' in a company is rather different to 'pictures
> of
> > > ourselves' in a community like the perl6 one, which is almost
> inherently
> > > online and virtual. And the perl6 community is definitely
> multicultural.
> > > We have contributors from Europe, America and Asia that I can
> identify.
> > > So it would not be 'pretending' to have images of people from those
> > > regions. I would be quite happy to have pictures of actual perl6
> users,
> > > rather than 'aesthetically pleasing' stock photos. Why not use
> pictures
> > > from YAPC's and hackathons?
> > >
> > > Richard Hainsworth
> > >
> > > Hong Kong.
> > >
> > >
> > > On 14/08/18 12:32, Fritz Zaucker wrote:
> > > > I don’t think “aesthetically pleasing” implies “beautiful people”
> > > > (whatever that metric might be).
> > > > We try to use “aesthetically pleasing” pictures of ourselves on our
> > > > company website, both to make it more “personal” and so that
> visitors
> > > > “see” who we are. We (at least I) don’t think we are all super
> models
> > > > just because of that.
> > > > Unfortunately so far we were not successful in hiring women for our
> > > > company and we also didn’t have any none-caucasian applicants either.
> > > > I don’t think it would make sense to pretend to be a multi-cultural
> > > > company by choosing pictures with people not part of the company.
> > > > Although I understand the marketing aspect, I would strongly suggest
> > > > to not use “artificial” pictures. We (the Perl6 community) are who
> we
> > > > are. And I also would strongly recommend to use good quality
> pictures
> > > > (as Perl6 wants to be a high quality language).
> > > > So, by all means let’s take many pictures showing off the Perl(6)
> > > > community and then choose good ones from that with as much diversity
> > > > as there is.
> > > > Cheers,
> > > > Fritz
> > > >
> > > > Fritz Zaucker
> > > > Platanen 42
> > > > 4600 Olten
> > > > +41 62 212 7712
> > > > +41 79 675 0630
> > > >
> > > > > On 14 Aug 2018, at 06:03, Richard Hainsworth

**Comment by nxadm** [comment]
There are more responses from after the conversation was locked than from before, so I propose to reopen it to non-members.

On the subject itself, @tbrowder's proposal wasn't calling the inquisition on the marketing material, but in my opinion observing that the stock photography does correspond with:
- who we are (we *are* a very diverse community).
- what we aim to be (cfr. camelia discussion).

I understand that there aren't many quality pictures available (from a technical-photographic point of view), but pictures from the community is something to strive for.

**Comment by JJ** [comment]
I've taken quite a few at the preconf meetup. They obviously reflect who we
are, but they also reflect the diversity of our community. I'll keep at
that in the next few days

**Comment by coke** [comment]
Anyone remember the backlash in the past when using conference pictures? I have a only a vague recollection that makes me want to suggest getting approval from those in the shots if they’re to be used for marketing.

**Comment by AlexDaniel** [comment]
Unlocked because it seems like we really want to discuss this, so a comment or two from others won't hurt I think.

**Comment by finanalyst** [comment]
We seem to be on the same page here.

I too would like to see photos of people, particularly those who have 
contributed so much to Perl6.

It's not entirely off-topic - that is not getting applications from 
women - because it seems to me that is the result of marketing. If a 
woman sees a company full of guys, is she going to apply? Would she not 
feel out of place if she does get the job.

So pictures of our actual community, which I know includes women, 
transgender, men, Asian, European, American, young, old, would be great 
marketing.

Regards.

**Comment by finanalyst** [comment]
a) there is always going to be a critic!

b) looking at only one criterion, eg. reality (no matter what the 
quality of the photo) vs quality (pandering to the tastes of the 
photographer) will generate fiery remarks from someone with another 
standard.

c) a transparent balance is ideal as someone has to make a choice

But if the images chosen are clearly an attempt at balance, critics are 
disempowered.

**Comment by zaucker** [comment]
On Tue, 14 Aug 2018, Richard Hainsworth wrote:

> We seem to be on the same page here.

That's what I thought :-)

> I too would like to see photos of people, particularly those who have
> contributed so much to Perl6.
>
> It's not entirely off-topic - that is not getting applications from women
> - because it seems to me that is the result of marketing.  If a woman sees
> a company full of guys, is she going to apply?  Would she not feel out of
> place if she does get the job.

I think the main reason is that at least around here there just are not many
women getting into computer science in the first place.

Well, there are only 5 IT guysus in our company, so 1 women would already be
about 17% of the staff.

And marketing our company with pictures of none-existing women is not really
an option I think.

We occasionally have female interns. A couple of years ago we had a
really brilliant one. Unfortunately, we could not convince here to pursue a
technical carrer :-(

But I think this discussion is getting a bit off-topic, as our main concern
is Perl6 marketing.

> So pictures of our actual community, which I know includes women,
> transgender, men, Asian, European, American, young, old, would be great
> marketing.

Yes. And if this has some side-effect on recruiting, that would be great.

Cheers,
Fritz

> On 14/08/18 14:44, Fritz Zaucker wrote:
>> I do agree that we should not use stock photos. Larry instead of
>> Richard Gere, Jonathan instead of Sean Connery, Liz and Wendy instead
>> of The Netherlands next super model, etc.
>>
>> Btw, some Perl6 community members are hard to identify at all, because
>> they only appear with cute nick names and photos are hard to find if
>> at all. Not sure what that means, I’d prefer to “know” the faces behind.
>>
>> I did say “let’s take many pictures and select aesthetically pleasing
>> ones”. With that I meant “high quality photos” (yes, that might be
>> subjective to some degree as well), but not “beauty” of the content
>> (for which there will probably be no common definition).
>>
>> As we are a small company there is no resistance of bias against
>> gender (whatever that might include) nor skin color to overcome as far
>> as I can tell. There might be other non-technical biases (or rather
>> selection criteria) such as ability to communicate not only on a
>> technical but also personal level and preferences (like language).
>>
>> And as I said, not having any applications by women just makes the
>> whole point mute.
>>
>> Cheers,
>> Fritz
>>
>>> On 14 Aug 2018, at 06:56, Richard Hainsworth
>> <notifications@github.com> wrote:
>>>
>>> If you do not understand a metric for 'beautiful people', how then do
>>> you have one for 'aesthetically pleasing'? They are both subjective
>>> categories that are intrinsically difficult to define, but which most
>>> people can use.
>>>
>>> "We use ...  pictures of ourselves'!  And 'we were not successful in
>>> hiring women ...  non-caucasian ...' Perhaps you do not have a good
>>> approach?  In my company I have a woman engineer who is far better than
>>> any of the male engineers we hired before, but we had to argue hard to
>>> hire her because of an inherent prejudice that women cant be
>>> engineers!!!
>>>
>>> 'Pictures of ourselves' in a company is rather different to 'pictures of
>>> ourselves' in a community like the perl6 one, which is almost inherently
>>> online and virtual.  And the perl6 community is definitely
>>> multicultural.

>>> We have contributors from Europe, America and Asia that I can identify.
>>> So it would not be 'pretending' to have images of people from those
>>> regions. I would be quite happy to have pictures of actual perl6 users,
>>> rather than 'aesthetically pleasing' stock photos. Why not use pictures
>>> from YAPC's and hackathons?
>>>
>>> Richard Hainsworth

-- 
Oetiker+Partner AG              tel: +41 62 775 9903 (direct)
Fritz Zaucker                        +41 62 775 9900 (switch board)
Aarweg 15                            +41 79 675 0630 (mobile)
CH-4600 Olten                   fax: +41 62 775 9905
Schweiz                         web: www.oetiker.ch

**Comment by zaucker** [comment]
That might be difficult for conference attendees who are not active in the
community. And some might be even in a difficult situation. We have a
(potential) customer for some Perl6 work whose employees are not even
allowed to mention what programming languages they use ...

I guess this would imply that one would has to select the photos carefully
and only use those on which all the identifiable people are "known" and can
be contacted.

On Tue, 14 Aug 2018, Will Coleda wrote:

> Anyone remember the backlash in the past when using conference pictures? 
> I have a only a vague recollection that makes me want to suggest getting
> approval from those in the shots if they’re to be used for marketing.

-- 
Oetiker+Partner AG              tel: +41 62 775 9903 (direct)
Fritz Zaucker                        +41 62 775 9900 (switch board)
Aarweg 15                            +41 79 675 0630 (mobile)
CH-4600 Olten                   fax: +41 62 775 9905
Schweiz                         web: www.oetiker.ch

**Comment by ijneb** [comment]
The stock photos of random people mindlessly staring at laptop screens for the shot are cheesy and unnecessary IMO.

**Comment by nxadm** [comment]
@Coke has a very good point.

**Comment by zoffixznet** [comment]
> Ditto for me as well regarding the language used; plus "locking the conversation" and declaring diversity discussions as "off topic" with respect to marketing feels very much against Perl 6 culture (at least the one I remember).

It's not offtopic, it's just for someone who does design for a living, I know exactly what these discussions lead to: a black female used in every photo to indicate how "diverse" we are. Any white male photo is a automatically "non-diverse" and should be replaced by a black female instead. Using someone's skin colour and genitals to pretend how "diverse" you are is racist by definition.

Despite writing miles of dialogue, no one in this thread seems to have bothered to look at the actual materials we have. Among all the materials, only 12% even have any photos to begin with and they contain:

- 1 x child white female
- 1 x adult latina female
- 1 x adult latino man
- 1 x adult white female

That's it. 4 pictures were ever used! And yet the OP think that's sufficient to judge whether there is an issue in diversity. What would those pictures look like if we didn't have this supposed "lack of diversity"? The answer is exactly what I mentioned: all four would contain black females.

Bean-counting for pretend-"diversity" is stupid.

> I too would like to see photos of people, particularly those who have
contributed so much to Perl6

Any photo used must be accompanied with a model release form, but unless these are taken by a professional photographer, the pictures are often too crap to be used anyway.

> Anyone remember the backlash in the past when using conference pictures?

Yes, I was eaten alive and harassed on multiple social media sites and said I won't ever use real people anymore. The whole "friendly community" goes out of the window as soon as you use someone's photo to promote the language.

**Comment by tbrowder** [comment]
I’m on your side, Zoffix, and I’m sorry I raised the issue.  Hypersensitivity seems to rule too much. My main thought at the time was to have a younger person’s photo, which could be a boy with darker coloring. The proposal was not made in anger or outrage, merely love for all of God’s children.

**Comment by AlexDaniel** [comment]
I think we are all on the same page here.

Feel free to reopen if there's new information. Filing a new ticket is also an option.
